### ISSUE TITLE
move to nuxt-community

### ISSUE THREAD

**Issue by pi0** [nuxt-community/cloudinary-module#1]
Hii :)

- [x] using module template
- [x] github invitation
  - [x] approve
- [x] npm invitation
  - [x] approve
  - [x] assign team for 
- [x] transfer to `nuxt-commuinity/cloudinary-module`
- [x] publish docs as cloudinary.nuxtjs.org
- [x] update references from `nuxt-cloudinary` to `@nuxtjs/cloudinary`
- [x] update references from `mayashavin/nuxt-cloudinary` to `nuxt-community/cloudinary-module`
- [x] publish initial version of package 
- [x] deprecate `nuxt-cloudinary`

**Comment by NickBolles** [comment]
@pi0 quick suggestion for that checklist above. Can you add "include typescript typings". It's something I'd expect from all Nuxt-community packages. Feel free to ping me if you ever needhelp with them.
