### ISSUE TITLE
Can't seem to get image width/height options to work

### ISSUE THREAD

**Issue by CodyBontecou** [nuxt-community/cloudinary-module#14]
Here's an example of the code I am working with: 

```python
computed: {
    metaImg() {
      return this.$cloudinary().url('hello-idioma/chat-bubble-logo', {
        width: 50,
        height: 50,
        fetchFormat: 'auto',
        responsive: true,
      })
    },
}
```

It's rendering the image I want, but I can't seem to change the size of the image, regardless of the width and height option values. What am I missing here?

**Comment by mayashavin** [comment]
@CodyBontecou Can you please send me the generate html code? I need more information on it. By the way, you can't use "responsive" together with "width" and "height", as `responsive` will override the given `width` to match the container.
