### ISSUE TITLE
Question: How does it work with the nuxtjs/content module?

### ISSUE THREAD

**Issue by francisceril** [nuxt-community/cloudinary-module#17]
Educate me, please.

I am using the **[Content](https://content.nuxtjs.org/)** module with front-matter, eg:

`content/products/product-one.md`
```
---
title: "Product One"
description: "Product description here."
category: "Shoes"
image: "jordan-1.jpg" // content/products/jordan-1.jpg
---
```

So with this module, would the image be automatically uploaded to Cloudinary and the URL will be set accordingly at build time?

Hope someone will provide an example on the docs. 😊

TIA

**Comment by mayashavin** [comment]
Hi @francisceril
Unfortunately this module currently doesn't support uploading automatically to Cloudinary while using it with content module. The new version will include upload :), which will be released this week.
Meanwhile, you can try to do it manually using the content hook and upload using upload url api of Cloudinary. I will post a more detailed example 😄

**Comment by mayashavin** [comment]
Hi @francisceril 

Please check out https://cloudinary.nuxtjs.org/integrations for the code snippets and instructions of how to use Cloudinary module and content module together in your use case. And don't forget to upgrade Cloudinary module to v1.0.0 :) 

Enjoy!
