### ISSUE TITLE
Native lazy loading not working

### ISSUE THREAD

**Issue by madsh93** [nuxt-community/cloudinary-module#26]
Adding a component with props.

            <Cld-image
              publicId="image"
              width="592"
              crop="fit"
              loading="lazy"
            />

However the snippet results in:
```` <img src="https://res.cloudinary.com/my_cloud/image/upload/w_592,c_fit/my-pic-id" /> ````
and not
```` <img src="https://res.cloudinary.com/my_cloud/image/upload/w_592,c_fit/my-pic-id" loading="lazy" /> ````

Changing loading="lazy" into anything else, makes the attribute show. Am I doing anything wrong, or is this a bug?

**Comment by mayashavin** [comment]
@madsh93 `loading=lazy` is actually a valid Cloudinary attribute, so you won't see it appears on the generated `img` element. However, in the background we do use the native lazy loading. So no worry about it. You can see an example here:
https://mayashavin.com/resources

All the images are lazy loaded, only when you scroll down you will see the images loaded :)

Hope it helps, and you can just use the props. All your images will be loaded lazy automatically :)
