### ISSUE TITLE
ERROR in ./.nuxt/cloudinary/plugin.client.js

### ISSUE THREAD

**Issue by genu** [nuxt-community/cloudinary-module#37]
I'm on Nuxt version `2.11.0` and I get this error:

`
ERROR in ./.nuxt/cloudinary/plugin.client.js
Module not found: Error: Can't resolve './cloudinary-api' in '/app/.nuxt/cloudinary'`

Looking at my `.nuxt` folder, and I see the structure like this:

There is an issue with the `cloudinary-api` js file being placed in the root rather than the `cloudinary` folder

![image](https://user-images.githubusercontent.com/928780/97517089-f5714100-196a-11eb-9157-65116c0c1b2a.png)

**Comment by keng0o** [comment]
same here

@mayashavin

**Comment by mayashavin** [comment]
@keng0o @genu That's weird. Which version are you using? The latest?

**Comment by genu** [comment]
@mayashavin I used the latest cloudinary module, and Nuxt 2.11.0 and this issue occurs.

This issues doesn't occurs, however, in newer versions of Nuxt. (I can't say for sure which version of Nuxt it starts working)

The issue may be that there is a possible API change in older Nuxt versions resulting in this weird behavior. Maybe add a fix for that, or put a minimum Nuxt version requirement.

Are you able to reproduce this at all?

**Comment by mayashavin** [comment]
@genu I tried Nuxt < 2.11 and it did happen. So yeah, it looks like something about the Nuxt API changes for earlier version. I will add a minimum Nuxt version requirement for now and see if we can add a fix without too much hassle :). Thanks

**Comment by mayashavin** [comment]
Ok, there is a change in convention from 2.13 onwards, where `fileName` becomes `filename` 😅. A fix will be on the way :)
