### ISSUE TITLE
Question: Is it possible to optimize images from local assets folder ?

### ISSUE THREAD

**Issue by lansolo99** [nuxt-community/cloudinary-module#39]
I’m not sure if it’s the place to post on this, but the documentation don’t tell about using images from local assets folder to perform Cloudinary transformations on the fly ?

The “programmatic usage” snippet in the “advanced” section show us how to batch upload a given folder to cloudinary on the server side.

For the time being, I’m using this workflow to upload all my local assets, then I dispatch the Cloudinary urls to proceed to image transformations within my templates.

But there is also the “fetchRemote” method to perform transformation for images not hosted on Cloudinary. 
I would expect this to work with a url build on the current environment, working both in development or production mode, but this doesn’t work.

This way, I won’t have to upload local assets on Cloudinary before I proceed to transformations.

Something like this :

```
this.$cloudinary.image.fetchRemote(
require(`@/assets/img/image.jpg`),
          { …

```

It’s not even documented, so I guess it’s not a workflow, but I wanted to have a confirmation..
Thanks

**Comment by mayashavin** [comment]
hi @lansolo99 

`fetchRemote` does not work that way. It only receives a **valid** URL, not a local created path. Valid URL means anything hosted on the internet that is not from Cloudinary.

`require('@/assets/img/image.jpg')` returns to you the dataset or the image module (depends on your configurations with webpack) from a local image. It points to your local image, and not build the actual hosted URL for that image.

Like stated in the documentation example, this is not a valid use case for `fetchRemote` :). In production and development mode, it won't work.

> but the documentation don’t tell about using images from local assets folder to perform Cloudinary transformations on the fly ?

I'm not sure I understand your request here :). On production, there are no local assets folder, you either need to host those assets somewhere, or upload them to Cloudinary using the build hook. The second option is a better approach. All the Cloudinary transformations can be done on the fly, but you can pre-define the transformation using `eager` when uploading them, so Cloudinary will create these transformations in advance. This way when you request for uploaded images with the same transformation on client side, the images will load even faster.

Your current workflow is correct :)

Hope it helps.

**Comment by lansolo99** [comment]
Thank you for your detailed answer, yes it helps to clarify what Cloudinary is used for.

It’s a bit hard to grasp the differenciation between a webpack pointer and a URL because these image files will be encompassed within the /dist folder after the built, thus hosted along the core app wherever we deploy it..

The build hook provides a convenient way to manage Cloudinary uploads for the local assets use-case, so I’m happy with that for the time being :)
