### ISSUE TITLE
Question: How can I use upload function?

### ISSUE THREAD

**Issue by enriqueaparicio-ph** [nuxt-community/cloudinary-module#40]
Hi there,

I was wondering if anyone can help me around **upload function.** I am trying to use _this.$cloudinary.upload(file, options,callback) but I do not how to get the first parameter. I know is the path of the file, but how can I get it from Nuxt.js template.

I have this on my template:
`<input
                      id="file"
                      ref="file"
                      type="file"
                      @change="handleFileUpload()"
                    />`
and 
```handleFileUpload() {
      this.file = this.$refs.file.files[0]
      console.log(this.file)
      // const instance = this.$cloudinary.upload(event.target.files[0], {
      //   folder: 'yryerty',
      //   upload_preset: 'tytyrrty',
      // })
      // console.log(instance)
    },
```

Could you help me how can I use that function please?

Thanks in advance

**Comment by mayashavin** [comment]
Hi @enriqueaparicio-ph 

The `file` you got from `this.refs.file.files[0]` still needs to be processed by using File API in order to have it converted to base64 data to pass to the upload function as data url. 

Here are some suggestions:

1. You don't need to use `refs` to get the input value. Use `e.target.files` is enough.
2. Use `FileReader` to create a reader.
3. Use `FileReader.readAsDataURL` to convert the data file to proper base64 data url.
4. Pass the generated `data` to `this.$cloudinary.upload`

```
const file = e.target.files[0];

/* Make sure file exists */
if (!file) return;

/* create a reader */
const readData = (f) =>  new Promise((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result);
    reader.readAsDataURL(f);
});

/* Read data */
const data = await readData(file);

/* upload the converted data */
const instance = this.$cloudinary.upload(data, {
  folder: 'yryerty',
  upload_preset: 'tytyrrty',
})
```

Hope it helps.

**Comment by enriqueaparicio-ph** [comment]
> Hi @enriqueaparicio-ph
> 
> The `file` you got from `this.refs.file.files[0]` still needs to be processed by using File API in order to have it converted to base64 data to pass to the upload function as data url.
> 
> Here are some suggestions:
> 
> 1. You don't need to use `refs` to get the input value. Use `e.target.files` is enough.
> 2. Use `FileReader` to create a reader.
> 3. Use `FileReader.readAsDataURL` to convert the data file to proper base64 data url.
> 4. Pass the generated `data` to `this.$cloudinary.upload`
> 
> ```
> const file = e.target.files[0];
> 
> /* Make sure file exists */
> if (!file) return;
> 
> /* create a reader */
> const readData = (f) =>  new Promise((resolve) => {
>     const reader = new FileReader();
>     reader.onloadend = () => resolve(reader.result);
>     reader.readAsDataURL(f);
> });
> 
> /* Read data */
> const data = await readData(file);
> 
> /* upload the converted data */
> const instance = this.$cloudinary.upload(data, {
>   folder: 'yryerty',
>   upload_preset: 'tytyrrty',
> })
> ```
> 
> Hope it helps.

Much appreciated.

All the best
