### ISSUE TITLE
Incorrect url returned from call to cloudinary from nuxt component.

### ISSUE THREAD

**Issue by mattbtay** [nuxt-community/cloudinary-module#43]
Making a call to cloudinary for a video returns a 500 response, while image returns 200. but the URL doesn't match the documentation.

`this.$cloudinary.image.url('01_nrwgrf')` returns `https://res.cloudinary.com/xxx-xxx/image/upload/f_auto,q_auto/01_nrwgrf`.

**Comment by mayashavin** [comment]
@mattbtay just to confirm, do you mean `this.$cloudinary.image.url` or `this.$cloudinary.video.url`? Because if it is `this.$cloudinary.image.url` then the generated link in the example is correct.

**Comment by mayashavin** [comment]
@mattbtay I just checked, it seems to be fine to me if you use `video.url()`. Below is a quick CodeSandbox demo I created.

[Code example](https://codesandbox.io/s/nuxt-cloudinary-video-url-example-2uh9u)

Can you please provide more details if it still happens to you?

**Comment by mattbtay** [comment]
Yes, the demo works just, fine. must be something on my end.
