### ISSUE TITLE
Compile Fail

### ISSUE THREAD

**Issue by chasedougherty4628** [nuxt-community/cloudinary-module#46]
Project wouldn't compile after following the setup guide for Nuxt:
1. yarn add @nuxtjs/cloudinary
2. Add @nuxtjs/cloudinary as a module in modules sections of nuxt.config.js
 - Project built successfully at this point
3. Add cloudinary configuration inside of nuxt.config.js

ERROR  Failed to compile with 1 errors
This relative module was not found ./cloudinary-api in ./.nuxt/cloudinary/plugin.client.js

Can confirm that cloudinary-api.js was in the same directory as plugin.client.js

The project is on Nuxt Version 2.12.2

Here's the configuration in nuxt.config.js
`modules: [
    '@nuxtjs/axios',
    '@nuxtjs/auth',
    '@nuxtjs/dotenv',
    '@nuxtjs/proxy',
    '@nuxtjs/gtm',
    '@nuxtjs/cloudinary',
    [
      'nuxt-vuex-localstorage',
      {
        localStorage: ['cart'],
        sessionStorage: ['shopping'],
      },
    ],
  ],
  cloudinary: {
    cloudName: 'dq*******',
  },`

**Comment by mayashavin** [comment]
@chasedougherty4628 this is a known issue. You are using Nuxt version < 2.13 right? This is fixed in #37 I will release a minor  version today for this and the bundle size.

**Comment by mayashavin** [comment]
@chasedougherty4628 please use v1.0.2. It should be fixed. LMK if you have question :)

**Comment by chasedougherty4628** [comment]
Thanks @mayashavin! I'll upgrade
