### ISSUE TITLE
error config property to good compare the the doc

### ISSUE THREAD

**Issue by f3ltron** [nuxt-community/cloudinary-module#5]
https://github.com/nuxt-community/cloudinary-module/blob/master/lib/templates/plugin.client.js#L6

In the doc you set privateCdn but in the plugin at least in the client template, you call options.privateCDN and put it inside privateCdn

**Comment by mayashavin** [comment]
I think it was correctly documented https://cloudinary.nuxtjs.org/options#privatecdn, it was supposed to be `privatedCDN`.

**Comment by f3ltron** [comment]
you right i dont know why we put privateCdn like in the doc

**Comment by mayashavin** [comment]
It's a naming problem. But I do find a small bug in template generating in the client template when `privateCDN` doesn't present. :)
