### ISSUE TITLE
this.configurations.cloudName is undefined

### ISSUE THREAD

**Issue by YannFroment** [nuxt-community/cloudinary-module#54]
Hi,

I'm struggling with cloudName, it's undefined due to camel case, following documentation, what's wrong ? 

<img width="776" alt="Capture d’écran 2020-12-21 à 08 14 44" src="https://user-images.githubusercontent.com/20149591/102749787-e7d1a980-4364-11eb-96dc-67ccbd2c3da3.png">

KR

**Comment by SabihRehman** [comment]
same issue with me

**Comment by mayashavin** [comment]
Indeed it is a bug caused during the refactoring 🤦🏻‍♀️. I will release a fix now :).

**Comment by mayashavin** [comment]
@SabihRehman @YannFroment Please install `@nuxtjs/cloudinary@1.0.3-beta-2`. LMK if it works.
Fixed in #48

**Comment by YannFroment** [comment]
Thank you Maya <3
