### ISSUE TITLE
Typescript - upload() method not supported

### ISSUE THREAD

**Issue by JohnnyChenJiaHao** [nuxt-community/cloudinary-module#58]
Hi, i want to say that i appreciate the work you are doing!

I am using nuxt with typescript and followed your setup. It seems that the cloudinary upload() method is not supported for typescript (can be fixed by adding "/ @ts-ignore"):
![image](https://user-images.githubusercontent.com/22538063/103773975-22f1ff00-502c-11eb-8b78-3f1b0f5f6e00.png)

But the other api method such as image() works.

I was wondering if it is going to be added in the future or it is a bug?

Best regards,
Johnny

**Comment by mayashavin** [comment]
@JohnnyChenJiaHao oops thank you for reporting this :). It's a small bug in type declaration when I did the refactoring and migration to TypeScript. I will have it fixed in the next release!
Have a nice day!

**Comment by mayashavin** [comment]
@JohnnyChenJiaHao it's fixed in 1.0.3-beta-3. Let me know if there is any issue :)
