### ISSUE TITLE
Latest 1.0 Beta breaks

### ISSUE THREAD

**Issue by jhull** [nuxt-community/cloudinary-module#61]
Started over from scratch rebuilding my app that was working great for months, with the latest `1.0 beta` of the Cloudinary module that loaded, I was getting `this.$cloudinary is not a function`. Rolled back to `0.0.8` and it works fine again.

Latest and greatest on all Nuxt (`nuxt-edge: latest`)

**Comment by mayashavin** [comment]
@jhull Thanks for reporting. Please revert to 0.1.2. We are currently testing 1.0.3-beta-2 for TypeScript migration so it's not stable enough. I will release the stable version in the upcoming days :)
