### ISSUE TITLE
Auto quality and auto format are not part of URL?

### ISSUE THREAD

**Issue by katerlouis** [nuxt-community/cloudinary-module#70]
![image](https://user-images.githubusercontent.com/1983382/109527243-b9cebb00-7ab3-11eb-90e0-384cc4ed1e09.png)

You claim [here](https://cloudinary.nuxtjs.org/usage/optimize-image/) that `f_auto` and `q_auto` is added by default.
Yet, when I do this:

```vue
<cld-image public-id="DUMBO-Team-Twitter" />
```

 I get this html:
```html
<img src="https://res.cloudinary.com/dumbo-design/image/upload/DUMBO-Team-Twitter">
```

I expected some `f_auto` and `q_auto` somewhere in the url; or am I missing something here?

How can I get `<cld-image />` to use `f_auto` in order to get WebP images? 

The following doesn't work and I couldn't find a prop for that in the [official cloudinary vue components src code](https://github.com/cloudinary/cloudinary-vue/tree/master/src/components)

```vue
<cld-image public-id="DUMBO-Team-Twitter" format="auto" />
```

I'd appreciate some enlightment;

**Comment by mayashavin** [comment]
@katerlouis if you use the components then no, the URLs are not generated with `f_auto` and `q_auto`. The above note is meant for using `$cloudinary.image.url` only, as it is written in Optimizing image with `$cloudinary` section. 

You need to pass `fetchFormat="auto"` when using `cld-image` to have `f_auto` enabled.

Hope it helps
