### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by MaxPowerReforged** [nuxt-community/cloudinary-module#76]
Hi! I installed this wonderful module with Nuxt's latest version, but seems that babel runtime is broken, I am getting this error:

* @babel/runtime-corejs2/core-js/array/from in ./node_modules/cloudinary-vue/dist/Cloudinary.umd.js        friendly-errors 11:49:45
* @babel/runtime-corejs2/core-js/get-iterator in ./node_modules/cloudinary-vue/dist/Cloudinary.umd.js        friendly-errors 11:49:45
* @babel/runtime-corejs2/core-js/is-iterable in ./node_modules/cloudinary-vue/dist/Cloudinary.umd.js          friendly-errors 11:49:45
* @babel/runtime-corejs2/core-js/object/freeze in ./node_modules/cloudinary-vue/dist/Cloudinary.umd.js          friendly-errors 11:49:45
* @babel/runtime-corejs2/core-js/object/get-own-property-descriptor in ./node_modules/cloudinary-vue/dist/Cloudinary.umd.js
* @babel/runtime-corejs2/core-js/object/get-own-property-descriptors in ./node_modules/cloudinary-vue/dist/Cloudinary.umd.js
* @babel/runtime-corejs2/core-js/object/get-own-property-symbols in ./node_modules/cloudinary-vue/dist/Cloudinary.umd.js  friendly-errors 11:49:45
* @babel/runtime-corejs2/core-js/object/keys in ./node_modules/cloudinary-vue/dist/Cloudinary.umd.js        friendly-errors 11:49:45
* @babel/runtime-corejs2/core-js/symbol in ./node_modules/cloudinary-vue/dist/Cloudinary.umd.js               friendly-errors 11:49:45
* @babel/runtime-corejs2/core-js/symbol/iterator in ./node_modules/cloudinary-vue/dist/Cloudinary.umd.js     friendly-errors 11:49:45
* @soda/get-current-script in ./node_modules/cloudinary-vue/dist/Cloudinary.umd.js

**Comment by abusada** [comment]
same! getting this: ![CleanShot 2021-04-07 at 15 39 50](https://user-images.githubusercontent.com/2572320/113867695-88829280-97b7-11eb-9dc6-2a582e1199a8.jpg)

**Comment by m-haziq** [comment]
Same here!

**Comment by bjunc** [comment]
It appears that this is related to the underlying cloudinary-vue module; which [released 1.2.0](https://github.com/cloudinary/cloudinary-vue/releases/tag/1.2.0) recently.

**Comment by mayashavin** [comment]
Duplicate with #77 
Please delete your `node_modules` and reinstall to the latest version  of the module (beta-4). It should fix.
