### ISSUE TITLE
Ligthouse  tells me that cloudinary-vue uses unused javascript

### ISSUE THREAD

**Issue by Kamsou** [nuxt-community/cloudinary-module#99]
Hey, 

I use @nuxtjs/cloudinary,
And Lighthouse shows me unused code that comes from cloudinary-vue

![Capture d’écran 2022-02-04 à 16 05 12](https://user-images.githubusercontent.com/41164034/152552825-6e5161e3-5908-4235-9f5f-e4f0341df130.png)

Would it be related to an update of this package from @nuxtjs/cloudinary ?

Thanks,
Camille

**Comment by mayashavin** [comment]
@Kamsou hi, if you turn on "useComponent" flag in nuxt.config.js, it will include cloudinary-vue. If you don't use any Cloudinary component from this package, just turn useComponent off and it should solve the problem.
